-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Клиенты"
(
    "id клиента" serial NOT NULL,
    "Название организации" character varying(100) NOT NULL,
    "Адрес" character varying(100) NOT NULL,
    "Номер телефона" character varying(20) NOT NULL,
    "Адрес электронной почты" character varying(50) NOT NULL,
    CONSTRAINT "Клиенты_pkey" PRIMARY KEY ("id клиента")
);

CREATE TABLE IF NOT EXISTS public."Оплаты"
(
    "id оплаты" serial NOT NULL,
    "Сумма" double precision,
    "Дата оплаты" date,
    "Способ оплаты" character varying(20),
    "id клиента" serial NOT NULL,
    "id транспортной операции" serial NOT NULL,
    CONSTRAINT "Оплаты_pkey" PRIMARY KEY ("id оплаты")
);

CREATE TABLE IF NOT EXISTS public."Водители"
(
    "id водителя" serial NOT NULL,
    "ФИО" character varying(60) NOT NULL,
    "Возраст" integer NOT NULL,
    "Стаж вождения" integer NOT NULL,
    "Номер водительского удостоверения" character varying(30) NOT NULL,
    "id транспортной операции" serial NOT NULL,
    CONSTRAINT "Водители_pkey" PRIMARY KEY ("id водителя")
);

CREATE TABLE IF NOT EXISTS public."Маршруты"
(
    "id маршрута" serial NOT NULL,
    "Точка отправления" character varying(20) NOT NULL,
    "Точка прибытия" character varying(20) NOT NULL,
    "Расстояние" double precision NOT NULL,
    "Время в пути" time without time zone NOT NULL,
    CONSTRAINT "Маршруты_pkey" PRIMARY KEY ("id маршрута")
);

CREATE TABLE IF NOT EXISTS public."Транспортные средства"
(
    "id транспортного средства" serial NOT NULL,
    "Производитель" character varying(20) NOT NULL,
    "Модель" character varying(20) NOT NULL,
    "Грузоподъёмность" double precision NOT NULL,
    "Регистрационный номер" character varying(10) NOT NULL,
    "id транспортной операции" serial NOT NULL,
    CONSTRAINT "Транспортные средства_pkey" PRIMARY KEY ("id транспортного средства")
);

CREATE TABLE IF NOT EXISTS public."Грузы"
(
    "id груза" serial NOT NULL,
    "Название" character varying(30) NOT NULL,
    "Вес" double precision NOT NULL,
    "Объём" double precision,
    "Дата погрузки" date,
    "id транспортной операции" serial NOT NULL,
    CONSTRAINT "Грузы_pkey" PRIMARY KEY ("id груза")
);

CREATE TABLE IF NOT EXISTS public."Транспортные операции"
(
    "id транспортной операции" serial NOT NULL,
    "Статус" character varying(15) NOT NULL,
    "Ожидаемое время доставки" time without time zone,
    "Дата прибытия" date,
    "id маршрута" serial NOT NULL,
    CONSTRAINT "Транспортные операции_pkey" PRIMARY KEY ("id транспортной операции")
);

CREATE TABLE IF NOT EXISTS public."Грузы-Транспортные средства"
(
    id serial NOT NULL,
    "id груза" serial NOT NULL,
    "id транспортного средства" serial NOT NULL,
    CONSTRAINT "Грузы-Транспортные средства_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Клиенты-Транспортные операции"
(
    id serial NOT NULL,
    "id клиента" serial NOT NULL,
    "id транспортной операции" serial NOT NULL,
    CONSTRAINT "Клиенты-Транспортные операции_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Оплаты"
    ADD CONSTRAINT "Клиенты_fkey" FOREIGN KEY ("id клиента")
    REFERENCES public."Клиенты" ("id клиента") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Оплаты"
    ADD CONSTRAINT "Транспортные операции_fkey" FOREIGN KEY ("id транспортной операции")
    REFERENCES public."Транспортные операции" ("id транспортной операции") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Водители"
    ADD CONSTRAINT "Транспортные операции_fkey" FOREIGN KEY ("id транспортной операции")
    REFERENCES public."Транспортные операции" ("id транспортной операции") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Транспортные средства"
    ADD CONSTRAINT "Транспортные операции_fkey" FOREIGN KEY ("id транспортной операции")
    REFERENCES public."Транспортные операции" ("id транспортной операции") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Грузы"
    ADD CONSTRAINT "Транспортные операции_fkey" FOREIGN KEY ("id транспортной операции")
    REFERENCES public."Транспортные операции" ("id транспортной операции") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Транспортные операции"
    ADD CONSTRAINT "Маршруты_fkey" FOREIGN KEY ("id маршрута")
    REFERENCES public."Маршруты" ("id маршрута") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Грузы-Транспортные средства"
    ADD CONSTRAINT "Грузы_fkey" FOREIGN KEY ("id груза")
    REFERENCES public."Грузы" ("id груза") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Грузы-Транспортные средства"
    ADD CONSTRAINT "Транспортные средства_fkey" FOREIGN KEY ("id транспортного средства")
    REFERENCES public."Транспортные средства" ("id транспортного средства") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Клиенты-Транспортные операции"
    ADD CONSTRAINT "Клиенты_fkey" FOREIGN KEY ("id клиента")
    REFERENCES public."Клиенты" ("id клиента") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Клиенты-Транспортные операции"
    ADD CONSTRAINT "Транспортные операции_fkey" FOREIGN KEY ("id транспортной операции")
    REFERENCES public."Транспортные операции" ("id транспортной операции") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;